name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Install CodeClimate Coverage Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
    - name: Build Docker container
      run: |
        ./scripts/build.sh
    - name: Run Test and report Coverage
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.aws_key_dev }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_dev }}
        CC_TEST_REPORTER_ID: ${{ secrets.test_report_id }}
      run: |
        ./cc-test-reporter before-build
        ./scripts/test.sh -k ${AWS_ACCESS_KEY_ID} -s ${AWS_SECRET_ACCESS_KEY}
        ./cc-test-reporter after-build --exit-code $?